DROP TABLE IF EXISTS ENGAPP_GITHUB_ISSUES;
DROP TABLE IF EXISTS ENGAPP_GITHUB_ISSUES_H;

DROP TABLE IF EXISTS ENGAPP_ISSUE_COUNT;
-- DROP TABLE IF EXISTS ENGAPP_ISSUE_COUNT_H;

DROP TABLE IF EXISTS ENGAPP_GITHUB_REPOSITORIES;
DROP TABLE IF EXISTS ENGAPP_GITHUB_REPOSITORIES_H;

DROP TABLE IF EXISTS ENGAPP_GITHUB_ORGANIZATIONS;
DROP TABLE IF EXISTS ENGAPP_GITHUB_ORGANIZATIONS_H;

DROP TABLE IF EXISTS ENGAPP_TEAMS;
DROP TABLE IF EXISTS ENGAPP_TEAMS_H;


