DELETE FROM ENGAPP_GITHUB_ISSUES;
DELETE FROM ENGAPP_GITHUB_ISSUES_H;

DELETE FROM ENGAPP_ISSUE_COUNT;
-- DELETE FROM ENGAPP_ISSUE_COUNT_H;

DELETE FROM ENGAPP_GITHUB_REPOSITORIES;
DELETE FROM ENGAPP_GITHUB_REPOSITORIES_H;

DELETE FROM ENGAPP_GITHUB_ORGANIZATIONS;
DELETE FROM ENGAPP_GITHUB_ORGANIZATIONS_H;

DELETE FROM ENGAPP_TEAMS;
DELETE FROM ENGAPP_TEAMS_H;


